### ISSUE TITLE
Trouble installing qslim on Mac OSX

### ISSUE THREAD

**Issue by augori** [alecjacobson/qslim#1]
Hi,  I'm not sure if I'm doing something wrong, but here's what's happening.  I _think_ I've installed fltk successfully, but when i run the last "make" command, I get the following linking error.  This is the last few lines:   I pasted the whole thing at the bottom of this message.
      Fl::x() in libfltk.a(Fl_cocoa.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [qvis] Error 1

I would be okay with just using the command line version. When I do "make qslim" it says it's up to date.   Then when I type the command "qslim" in the directory where qslim resides, I get a "command not found" response.

I'm running OS X Yosemite.  Thanks in advance for your help!
## Here's the full error...

Undefined symbols for architecture x86_64:
  "_NSApp", referenced from:
      fl_open_display() in libfltk.a(Fl_cocoa.o)
      DataReady::DataReadyThread(void_) in libfltk.a(Fl_cocoa.o)
      fl_ready() in libfltk.a(Fl_cocoa.o)
      do_timer(__CFRunLoopTimer_, void_) in libfltk.a(Fl_cocoa.o)
      fl_wait(double) in libfltk.a(Fl_cocoa.o)
      -[FLTextView insertText:] in libfltk.a(Fl_cocoa.o)
      -[FLTextView doCommandBySelector:] in libfltk.a(Fl_cocoa.o)
      ...
  "_NSBeep", referenced from:
      fl_beep(int) in libfltk.a(fl_ask.o)
  "_NSDeviceRGBColorSpace", referenced from:
      Fl::paste(Fl_Widget&, int, char const_) in libfltk.a(Fl_cocoa.o)
      Fl_X::CGBitmapContextToTIFF(CGContext_) in libfltk.a(Fl_cocoa.o)
      Fl_X::set_cursor(Fl_RGB_Image const_, int, int) in libfltk.a(Fl_cocoa.o)
      CGBitmapContextToNSImage(CGContext_) in libfltk.a(Fl_cocoa.o)
  "_NSDeviceWhiteColorSpace", referenced from:
      Fl_X::set_cursor(Fl_RGB_Image const_, int, int) in libfltk.a(Fl_cocoa.o)
  "_NSDragPboard", referenced from:
      Fl::dnd() in libfltk.a(Fl_cocoa.o)
  "_NSFilenamesPboardType", referenced from:
      -[FLView performDragOperation:] in libfltk.a(Fl_cocoa.o)
      Fl_X::make(Fl_Window_) in libfltk.a(Fl_cocoa.o)
  "_NSFontAttributeName", referenced from:
      Fl_Paged_Device::print_window(Fl_Window_, int, int) in libfltk.a(Fl_cocoa.o)
  "_NSGraphicsContextDestinationAttributeName", referenced from:
      Fl::paste(Fl_Widget&, int, char const_) in libfltk.a(Fl_cocoa.o)
  "_NSIntegralRect", referenced from:
      Fl::paste(Fl_Widget&, int, char const_) in libfltk.a(Fl_cocoa.o)
  "_NSPasteboardTypeString", referenced from:
      __GLOBAL__sub_I_Fl_cocoa.mm in libfltk.a(Fl_cocoa.o)
  "_NSStringPboardType", referenced from:
      __GLOBAL__sub_I_Fl_cocoa.mm in libfltk.a(Fl_cocoa.o)
  "_NSWindowDidMoveNotification", referenced from:
      -[FLAppDelegate applicationDidChangeScreenParameters:] in libfltk.a(Fl_cocoa.o)
  "_NSWindowWillCloseNotification", referenced from:
      fl_open_display() in libfltk.a(Fl_cocoa.o)
  "_NSZeroPoint", referenced from:
      Fl_X::make(Fl_Window_) in libfltk.a(Fl_cocoa.o)
  "_NSZeroSize", referenced from:
      CGBitmapContextToNSImage(CGContext_) in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSAffineTransform", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSApplication", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSAttributedString", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSBitmapImageRep", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSBundle", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSColor", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSCursor", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSEvent", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSFont", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSGraphicsContext", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSImage", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSMenu", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSMenuItem", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSNotificationCenter", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSPDFImageRep", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSPICTImageRep", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSPasteboard", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSPrintInfo", referenced from:
      objc-class-ref in libfltk.a(Fl_Quartz_Printer.o)
  "_OBJC_CLASS_$_NSPrintPanel", referenced from:
      objc-class-ref in libfltk.a(Fl_Quartz_Printer.o)
  "_OBJC_CLASS_$_NSProcessInfo", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSRunningApplication", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSScreen", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSTextView", referenced from:
      _OBJC_CLASS_$_FLTextView in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSThread", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSView", referenced from:
      _OBJC_CLASS_$_FLView in libfltk.a(Fl_cocoa.o)
  "_OBJC_CLASS_$_NSWindow", referenced from:
      objc-class-ref in libfltk.a(Fl_cocoa.o)
      _OBJC_CLASS_$_FLWindow in libfltk.a(Fl_cocoa.o)
  "_OBJC_METACLASS_$_NSTextView", referenced from:
      _OBJC_METACLASS_$_FLTextView in libfltk.a(Fl_cocoa.o)
  "_OBJC_METACLASS_$_NSView", referenced from:
      _OBJC_METACLASS_$_FLView in libfltk.a(Fl_cocoa.o)
  "_OBJC_METACLASS_$_NSWindow", referenced from:
      _OBJC_METACLASS_$_FLWindow in libfltk.a(Fl_cocoa.o)
  "MxGUI::initialize(int, char**, Fl_Menu_Item*, int, int)", referenced from:
      MxStdGUI::initialize(int, char**, Fl_Menu_Item_, int, int) in libmix.a(MxStdGUI.o)
  "MxGUI::cmdline_option(int, char__, int&)", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::add_toggle_menu(char const_, int, bool&, int)", referenced from:
      _main in qvis.o
      MxStdGUI::initialize(int, char*_, Fl_Menu_Item_, int, int) in libmix.a(MxStdGUI.o)
  "MxGUI::update_animation()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::save_view_to_file()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::load_view_from_file()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::run()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::status(char const_, ...)", referenced from:
      cb_target(void_, int) in qvis.o
      _main in qvis.o
  "MxGUI::current", referenced from:
      cb_color(Fl_Menu__, double_) in libmix.a(MxStdGUI.o)
      cb_model(Fl_Menu__, int) in libmix.a(MxStdGUI.o)
  "MxGUI::key_press(int)", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::MxGUI()", referenced from:
      MxStdGUI::MxStdGUI() in libmix.a(MxStdGUI.o)
  "typeinfo for MxGUI", referenced from:
      typeinfo for MxStdGUI in libmix.a(MxStdGUI.o)
  "__objc_empty_cache", referenced from:
      _OBJC_CLASS_$_FLWindow in libfltk.a(Fl_cocoa.o)
      _OBJC_METACLASS_$_FLWindow in libfltk.a(Fl_cocoa.o)
      _OBJC_METACLASS_$_FLTextView in libfltk.a(Fl_cocoa.o)
      _OBJC_CLASS_$_FLTextView in libfltk.a(Fl_cocoa.o)
      _OBJC_CLASS_$_FLWindowDelegate in libfltk.a(Fl_cocoa.o)
      _OBJC_METACLASS_$_FLWindowDelegate in libfltk.a(Fl_cocoa.o)
      _OBJC_METACLASS_$_FLAppDelegate in libfltk.a(Fl_cocoa.o)
      ...
  "_objc_msgSend", referenced from:
      fl_open_display() in libfltk.a(Fl_cocoa.o)
      DataReady::DataReadyThread(void_) in libfltk.a(Fl_cocoa.o)
      fl_ready() in libfltk.a(Fl_cocoa.o)
      do_timer(__CFRunLoopTimer_, void_) in libfltk.a(Fl_cocoa.o)
      -[FLWindow convertBaseToScreen:] in libfltk.a(Fl_cocoa.o)
      -[FLWindow initWithFl_W:contentRect:styleMask:] in libfltk.a(Fl_cocoa.o)
      fl_wait(double) in libfltk.a(Fl_cocoa.o)
      ...
  "_objc_msgSendSuper2", referenced from:
      -[FLWindow initWithFl_W:contentRect:styleMask:] in libfltk.a(Fl_cocoa.o)
      -[FLView init] in libfltk.a(Fl_cocoa.o)
  "_objc_msgSend_stret", referenced from:
      fl_open_display() in libfltk.a(Fl_cocoa.o)
      -[FLWindow convertBaseToScreen:] in libfltk.a(Fl_cocoa.o)
      -[FLWindowDelegate windowDidMove:] in libfltk.a(Fl_cocoa.o)
      update_e_xy_and_e_xy_root(NSWindow_) in libfltk.a(Fl_cocoa.o)
      -[FLWindowDelegate windowDidResize:] in libfltk.a(Fl_cocoa.o)
      -[FLAppDelegate applicationDidChangeScreenParameters:] in libfltk.a(Fl_cocoa.o)
      Fl::x() in libfltk.a(Fl_cocoa.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [qvis] Error 1

**Comment by alecjacobson** [comment]
Seems like you're missing from Apple frameworks

**Comment by augori** [comment]
Thank you for the fast response!  I have to admit though that I don't know what that means.  Can you recommend somewhere I should go to download and install Apple Frameworks?   I found this page, but am not sure where to start:  https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/VersionInformation.html#//apple_ref/doc/uid/20002255-BCIECADD

**Comment by alecjacobson** [comment]
You should already have everything. Especially if you've installed XCode.
Typically you just need to add `-framework [NameOfFramework]` to your
compiler flags. `CoreFoundation`, `AppKit` and `IOKit` are often the
missing ones.

**Comment by augori** [comment]
You're right.  It looks like I do already have the frameworks you mentioned. Sorry to keep bugging you but I can't seem to get this right.   

 If I understand you correctly, I should add the framework flags to the gcc commands in the Makefile as shown below.  Or should I be only trying one framework at a time?  I'm still getting an error 
-------------------begin makefile-----------
include ../../mixkit/mix-config

SRCS = cmdline.cxx main.cxx output.cxx qslim.cxx
QVIS_SRCS = cmdline.cxx main.cxx output.cxx qvis.cxx
OBJS = $(SRCS:.cxx=.o)
QVIS_OBJS = $(QVIS_SRCS:.cxx=.o)

all: qslim qvis

qslim : $(OBJS) ../../mixkit/src/libmix.a
        $(CXX) -o qslim $(OBJS) $(LDFLAGS) $(LIBMIX) -lm -lfltk_gl -framework CoreFoundation -framework AppKit -framework IOKit

qvis : $(QVIS_OBJS) ../../mixkit/src/libmix.a
        $(CXX) -o qvis $(QVIS_OBJS) $(LDFLAGS) $(LIBMIX) $(GUI_LIBS) -lm -lfltk_gl -framework CoreFoundation -framework AppKit -framework IOKit

```
    $(FLTKCONFIG) --post qvis
```

clean:
        -$(RM) -f $(OBJS) qslim qvis
        -cat /dev/null > Makefile.dep

depend:
        $(CXX_DEPEND) $(SRCS) $(QVIS_SRCS) > Makefile.dep

-include Makefile.dep
---------------end makefile-------------------

I cleaned an ran it again but I think I'm still getting a linker error...
g++ -o qvis cmdline.o main.o output.o qvis.o -L/opt/local/lib -L/Users/lgtateos/Downloads/qslim-master/libgfx/src  -L/Users/lgtateos/Downloads/qslim-master/mixkit/src -lmix -lgfx -lfltk -lz -framework AGL -framework OpenGL -framework Carbon -framework ApplicationServices  -lm -lfltk_gl -framework CoreFoundation -framework AppKit -framework IOKit
ld: warning: directory not found for option '-L/opt/local/lib'
Undefined symbols for architecture x86_64:
  "MxGUI::initialize(int, char**, Fl_Menu_Item*, int, int)", referenced from:
      MxStdGUI::initialize(int, char**, Fl_Menu_Item_, int, int) in libmix.a(MxStdGUI.o)
  "MxGUI::cmdline_option(int, char__, int&)", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::add_toggle_menu(char const_, int, bool&, int)", referenced from:
      _main in qvis.o
      MxStdGUI::initialize(int, char*_, Fl_Menu_Item_, int, int) in libmix.a(MxStdGUI.o)
  "MxGUI::update_animation()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::save_view_to_file()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::load_view_from_file()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::run()", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::status(char const_, ...)", referenced from:
      cb_target(void_, int) in qvis.o
      _main in qvis.o
  "MxGUI::current", referenced from:
      cb_color(Fl_Menu__, double_) in libmix.a(MxStdGUI.o)
      cb_model(Fl_Menu__, int) in libmix.a(MxStdGUI.o)
  "MxGUI::key_press(int)", referenced from:
      vtable for GUI in qvis.o
      vtable for MxStdGUI in libmix.a(MxStdGUI.o)
  "MxGUI::MxGUI()", referenced from:
      MxStdGUI::MxStdGUI() in libmix.a(MxStdGUI.o)
  "typeinfo for MxGUI", referenced from:
      typeinfo for MxStdGUI in libmix.a(MxStdGUI.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [qvis] Error 1

---

When I do an ls on /System/Library/Frameworks I get the following:
AGL.framework               IOKit.framework
AVFoundation.framework          IOSurface.framework
AVKit.framework             ImageCaptureCore.framework
Accelerate.framework            ImageIO.framework
Accounts.framework          InputMethodKit.framework
AddressBook.framework           InstallerPlugins.framework
AppKit.framework            InstantMessage.framework
AppKitScripting.framework       JavaFrameEmbedding.framework
AppleScriptKit.framework        JavaScriptCore.framework
AppleScriptObjC.framework       JavaVM.framework
ApplicationServices.framework       Kerberos.framework
AudioToolbox.framework          Kernel.framework
AudioUnit.framework         LDAP.framework
AudioVideoBridging.framework        LatentSemanticMapping.framework
Automator.framework         LocalAuthentication.framework
CFNetwork.framework         MapKit.framework
CalendarStore.framework         MediaAccessibility.framework
Carbon.framework            MediaLibrary.framework
CloudKit.framework          MediaToolbox.framework
Cocoa.framework             Message.framework
Collaboration.framework         MultipeerConnectivity.framework
CoreAudio.framework         NetFS.framework
CoreAudioKit.framework          NetworkExtension.framework
CoreAuthentication.framework        NotificationCenter.framework
CoreBluetooth.framework         OSAKit.framework
CoreData.framework          OpenAL.framework
CoreFoundation.framework        OpenCL.framework
CoreGraphics.framework          OpenDirectory.framework
CoreLocation.framework          OpenGL.framework
CoreMIDI.framework          PCSC.framework
CoreMIDIServer.framework        PreferencePanes.framework
CoreMedia.framework         PubSub.framework
CoreMediaIO.framework           Python.framework
CoreServices.framework          QTKit.framework
CoreTelephony.framework         Quartz.framework
CoreText.framework          QuartzCore.framework
CoreVideo.framework         QuickLook.framework
CoreWLAN.framework          QuickTime.framework
CryptoTokenKit.framework        Ruby.framework
DVComponentGlue.framework       SceneKit.framework
DVDPlayback.framework           ScreenSaver.framework
DirectoryService.framework      Scripting.framework
DiscRecording.framework         ScriptingBridge.framework
DiscRecordingUI.framework       Security.framework
DiskArbitration.framework       SecurityFoundation.framework
DrawSprocket.framework          SecurityInterface.framework
EventKit.framework          ServiceManagement.framework
ExceptionHandling.framework     Social.framework
FWAUserLib.framework            SpriteKit.framework
FinderSync.framework            StoreKit.framework
ForceFeedback.framework         SyncServices.framework
Foundation.framework            System.framework
GLKit.framework             SystemConfiguration.framework
GLUT.framework              TWAIN.framework
GSS.framework               Tcl.framework
GameController.framework        Tk.framework
GameKit.framework           VideoDecodeAcceleration.framework
Hypervisor.framework            VideoToolbox.framework
ICADevices.framework            WebKit.framework
IMCore.framework            module.map
IMServicePlugIn.framework       vecLib.framework
IOBluetooth.framework           vmnet.framework
IOBluetoothUI.framework

**Comment by alecjacobson** [comment]
Now it seems like it's not linking to the "mixkit" code from this project.

**Comment by augori** [comment]
How can I make it link to those files?

I think it's already linking to -L/Users/lgtateos/Downloads/qslim-master/mixkit/src

abc-MBA:qslim lgtateos$ ls -L/Users/lgtateos/Downloads/qslim-master/mixkit/src
Makefile        MxEdgeFilter.o      MxGUI.h         MxQMetric.cxx       MxStdSlim.h
MxAsp.cxx       MxFaceTree-2.cxx    MxGeoPrims.h        MxQMetric.h     MxStdSlim.o
MxAsp.h         MxFaceTree-2.o      MxGeom2D.cxx        MxQMetric.o     MxString.h
MxAsp.o         MxFaceTree.cxx      MxGeom2D.h      MxQMetric3.cxx      MxTimer.h
MxBlock.h       MxFaceTree.h        MxGeom2D.o      MxQMetric3.h        MxTriProject.cxx
MxBlock2.h      MxFaceTree.o        MxGeom3D.cxx        MxQMetric3.o        MxTriProject.o
MxBlock3.h      MxFeatureFilter.cxx MxGeom3D.h      MxQSlim.cxx     MxVec2.h
MxBlockModel.cxx    MxFeatureFilter.h   MxGeom3D.o      MxQSlim.h       MxVec3.h
MxBlockModel.h      MxFeatureFilter.o   MxHeap.cxx      MxQSlim.o       MxVec4.h
MxBlockModel.o      MxFitFrame-2.cxx    MxHeap.h        MxQVis3.cxx     MxVector.h
MxCamera.cxx        MxFitFrame-2.o      MxHeap.o        MxQVis3.o       libmix.a
MxCamera.h      MxFitFrame-vis.cxx  MxManipulator.h     MxRaster.h      mixcfg.h.in
MxCamera.o      MxFitFrame-vis.o    MxMat2.h        MxSMF.cxx       mixio.h
MxCmdParser.cxx     MxFitFrame.cxx      MxMat3-jacobi.cxx   MxSMF.h         mixmops.cxx
MxCmdParser.h       MxFitFrame.h        MxMat3-jacobi.o     MxSMF.o         mixmops.h
MxCmdParser.o       MxFitFrame.o        MxMat3.h        MxStack.h       mixmops.o
MxDualModel.cxx     MxFrame.cxx     MxMat4-jacobi.cxx   MxStdGUI.cxx        mixmsg.cxx
MxDualModel.h       MxFrame.h       MxMat4-jacobi.o     MxStdGUI.h      mixmsg.h
MxDualModel.o       MxFrame.o       MxMat4.h        MxStdGUI.o      mixmsg.o
MxDualSlim.cxx      MxGL.h          MxMath.h        MxStdModel.cxx      mixvops.h
MxDualSlim.h        MxGLDebug.cxx       MxMatrix.cxx        MxStdModel.h        stdmix.h
MxDualSlim.o        MxGLDebug.o     MxMatrix.h      MxStdModel.o
MxDynBlock.h        MxGLUtils.cxx       MxPropSlim.cxx      MxStdRender.cxx
MxEdgeFilter.cxx    MxGLUtils.h     MxPropSlim.h        MxStdRender.o
MxEdgeFilter.h      MxGLUtils.o     MxPropSlim.o        MxStdSlim.cxx

**Comment by anilkumar2444** [comment]
Facing kind of similar problem on ubuntu
I am trying to install Qslim on ubuntu,
I have installed autoconf,fltk, libgfx, mixkit library successfully, however I got the following two warnings while adding libgfx, but libgfx added successfully.

checking for FLTK library... no
checking for FLTK GL support... no

checking GL/glext.h usability... no
checking GL/glext.h presence... yes
configure: WARNING: GL/glext.h: present but cannot be compiled
configure: WARNING: GL/glext.h: check for missing prerequisite headers?
configure: WARNING: GL/glext.h: proceeding with the preprocessor's result
configure: WARNING: ## ------------------------------------ ##
configure: WARNING: ## Report this to bug-autoconf@gnu.org. ##
configure: WARNING: ## ------------------------------------ ##

After this I tried installing Qslim. Then I got this error

/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:96: undefined reference to MxGUI::status(char const_, ...)' qvis.o: In functionmain':
/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:282: undefined reference to MxGUI::add_toggle_menu(char const_, int, bool&, int)' /home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:284: undefined reference toMxGUI::add_toggle_menu(char const*, int, bool&, int)'
/home/anil/Desktop/qslim-2.1/tools/qslim/qvis.cxx:312: undefined reference to `MxGUI::run()'

It looks like it is failing to link Qslim to libgfx.
It would be very grateful if somebody could help me with this. Thanks in advance.

**Comment by augori** [comment]
okay, I didn't get qvis working, but going back to my first problem which was, "I type the command "qslim" in the directory where qslim resides, I get a "command not found" response."  

Solution:
I simply needed to type ./qslim instead of just qslim.  This runs it and hangs, since there's no input. Ctrl+q to stop the run.   

To run it you need to know the flags and have some data in the right format (smf, that specifies vertices and faces in a particular way).

I found some smf  (e.g., cow.smf) input data here: (http://mgarland.org/research/quadrics.html)

./qslim -h        describes the usage....

QSlim surface simplification software.
Version 2.1 [Built May 19 2017].
Copyright (C) 1998-2002 Michael Garland.  See "COPYING.txt" for details.

usage: ./qslim <options> [filename]

Available options:
-O <n>         Optimal placement policy:
                       0=endpoints, 1=endormid, 2=line, 3=optimal [default]
-B <weight>    Use boundary preservation planes with given weight.
-W <n>         Quadric weighting policy:
                       0=uniform, 1=area [default], 2=angle
-t <n>         Set the target number of faces.
-F             Use face contraction instead of edge contraction.
-o <file>      Output final model to the given file.
-I <file>      Deferred file inclusion.
-m <penalty>   Set the penalty for bad meshes.
-c <ratio>     Set the desired compactness ratio.
-r             Enable history recording.
-M <format>    Select output format:
                       {smf, iv, vrml, pm, mmf, log}
-q		Be quiet.
-j             Join only; do not remove any faces.
-h             Print help.

Here's an example of running it to reduce cow.smf to 1000 faces and generate an smf output file (cow_reduced.smf):
./qslim -t 1000 -M smf cow.smf > ./cow_reduced.smf
