### ISSUE TITLE
Changing the Qslim to New Quadric Metric from Hoppe

### ISSUE THREAD

**Issue by LAR-UFSC** [alecjacobson/qslim#3]
I installed the Qslim from Michael Garland and it is working, although to my approach would be great if I can improve to the algorithm proposed by Hugues Hoppe (New Quadric Metric for Simplifying Meshes with Appearance Attributes) which consider the normal of the retails. 

There`s anyone tried it ? Or have the Hugues Hoppe algorithm ?

Thanks.

**Comment by alecjacobson** [comment]
I'm not planning to make any changes to this code, rather just keep it compiling for comparisons.

There's another implementation of qslim in libigl. There the energy is exposed and you could play around with it.
